[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn fiado_project.wsgi --workers 2 --timeout 120 --log-file -"
healthcheckPath = "/login/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
