# Generated by Django 4.2.16 on 2026-04-08 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total (R$)')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('faturado', models.BooleanField(default=False, verbose_name='Faturado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='clientes.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Consumo',
                'verbose_name_plural': 'Consumos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Preço no momento do consumo (histórico)', max_digits=10, verbose_name='Valor unitário (R$)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal (R$)')),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='consumos.consumo', verbose_name='Consumo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumo_itens', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item de consumo',
                'verbose_name_plural': 'Itens de consumo',
            },
        ),
    ]
