# Generated by Django 4.2.16 on 2026-04-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0001_initial'),
        ('consumos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='faturas.faturamensal', verbose_name='Fatura'),
        ),
    ]
