# Generated by Django 4.2.16 on 2026-04-08 18:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='clientes/fotos/', verbose_name='Foto')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, help_text='0 = sem limite definido', max_digits=10, verbose_name='Limite de crédito (R$)')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('bloqueado', 'Bloqueado'), ('inadimplente', 'Inadimplente')], default='ativo', max_length=20, verbose_name='Status')),
                ('token_qr', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token QR Code')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ClienteQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='clientes/qrcodes/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode_obj', to='clientes.cliente')),
            ],
        ),
    ]
